# Generated by Django 2.2.8 on 2020-01-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='rishabjmu@gmail.com', max_length=50),
        ),
    ]
